name: "Corporate Giveaways Buyers' Show"
favicon: null
layout_spectrum: 0.5276805872563273
typography_spectrum: 0.3529190912377089
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7851991872303188
  lightness: 0.8162055804859847
  saturation: 0.5067944873590022
  rhythmicContrast: 0.8041848961729556
purpose: []
